### PR TITLE
Update LAB_06-Implement_Network_Traffic_Management.md

### PR DESCRIPTION
**Pull request by mrep1085**
Ref: #394

Instructions are currently showing as:
image

### CODE REVIEW

**Comment by staleycyn** [comment]
Is the problem the indentation?

**Comment by mrep1085** [comment]
Possibly, but the third command is showing up differently as well. I believe it may be related to the "(execute one command at a time)" sharing the same line as the ```powershell. 

There's a similar issue with the instructions for #396 on Module 07.
image

**Comment by staleycyn** [comment]
I am not sure what the problem is that you are trying to fix. Does the command not run? Or you don't like visually how it looks?

**Comment by mrep1085** [comment]
Visually it looks off in our instructions. The command will work fine, but it could be cleaned up visually.

**Comment by staleycyn** [comment]
If this is just visual, I will close this until our next review next month.

**Pull request closed without merging**
