### PR TITLE
clarification

### PR DESCRIPTION
**Pull request by renaudwangler**
# Module: 04
## Lab: 04, task 4

Changes proposed in this pull request:

- I suggest we change a "note" information (which is in fact the synthesis of the next steps) to a "step" information.
-
-

### CODE REVIEW

**Comment by staleycyn** [comment]
Let's try to focus our repository Issues on things that **must** to be fixed. For example, UI changes, error messages, and broken steps. Thanks for understanding.

**Comment by renaudwangler** [comment]
Hello :)
Thank you for the quick answer. I think my proposal was not fully clear because I'm not an English native speaker ;)
The problem I had with sutdent on this lab yesterday was the mentionned "note" is in fact the abstract of the following steps : multiple students didn't understand the note and asked "how do I  do this test ?"
Our feeling is that this note is out of sequence....
(of course I understand the "issues focus" of this repo and would'nt have proposed a changed if I didi not encounter a problem during course teaching ;) )

**Comment by polichtm** [comment]
Hi Renaud,
I updated the content of the note to provide more clarity. 
Pls let me know if this works for you
rgds
Marcin

**Comment by renaudwangler** [comment]
Nice move : many thanks ;)

**Comment by polichtm** [comment]
You're very welcome
rgds
Marcin

**Pull request closed without merging**
