### PR TITLE
Update az104-02a-customRoleDefinition.json

### PR DESCRIPTION
**Pull request by erpujabaidya**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by polichtm** [comment]
Would you mind clarifying why you would want to replace a placeholder with the ID of your subscription? Do you really intend for everyone else to use your subscription?
rgds
Marcin

**Comment by erpujabaidya** [comment]
Is there any problem? I forked it to my account as I thought I have upgrade
the subscription I'd there. If there is any problem please let me know.

Regards,
Puja

**Comment by polichtm** [comment]
Hi Puja,
you submitted a PR to the main repo. I assume this wasn't your intention.
rgds
Marcin

**Comment by erpujabaidya** [comment]
That's true.

**Pull request closed without merging**
