### PR TITLE
Clarify on specific management group to move to in

### PR DESCRIPTION
**Pull request by tofusgh**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by polichtm** [comment]
This assumes that the subscription was originally part of the root management group. Can you advise what is your assumption based on?
rgds
Marcin

**Comment by tofusgh** [comment]
Hey Marcin,

This was a suggestion based on student feedback to be more clear...

-Tori

________________________________

**Comment by polichtm** [comment]
I can see the point, however, I don't believe we're in the position to make the assumption that the subscription was originally under the root (even though this is likely the case most of the time)
rgds
Marcin

**Comment by tofusgh** [comment]
Marcin,

Maybe we can say if this is new tenant it should be your Root MG?

-Tori

________________________________

**Pull request merged**
