### PR TITLE
Added links to interactive lab simulations in read.me and lab pages.

### PR DESCRIPTION
**Pull request by ejneuman**
Applies to all labs.  Added links to interactive lab simulations in read.me and lab pages.

### CODE REVIEW

**Comment by jubic** [comment]
The simulation is not playing.

**Comment by staleycyn** [comment]
Do you mean the link isn't working? It is working for me. Or maybe you mean one of the individual links isn't working? Please clarify.

**Comment by jubic** [comment]
The link is working, just that the simulation is not playable.

**Comment by staleycyn** [comment]
Did you click on the simulation that you want to play?

**Comment by jubic** [comment]
image
There is no play button in this simulation https://mslabs.cloudguides.com/guides/AZ-104%20Exam%20Guide%20-%20Microsoft%20Azure%20Administrator

Where as the individual lab simulations do
image
https://mslabs.cloudguides.com/guides/AZ-104%20Exam%20Guide%20-%20Microsoft%20Azure%20Administrator%20Exercise%201

**Comment by jubic** [comment]
Okay, didn't realize that hyperlinks are embedded in the "overview" simulation

**Comment by staleycyn** [comment]
Each lab page has the individual simulation link for that lab. Also in the future, please add an Issue to the repo so the concern can be tracked. Thanks.

**Pull request merged**
