### PR TITLE
Update LAB_08-Manage_Virtual_Machines.md

### PR DESCRIPTION
**Pull request by revpixel**
## Lab 08

Fixes # .

Changes proposed in this pull request:

Change the task to assign a public IP and a basic NSG (see comment)

### CODE REVIEW

**Comment by polichtm** [comment]
would you mind posting a screenshot of what you're referring to? Here is what I'm seeing
image

rgds
Marcin

**Comment by revpixel** [comment]
Sure. I'm teaching today so let me do this tonight and Screenshot the issue and post it tonight or tomorrow.

**Comment by revpixel** [comment]
Note two screenshots (If you follow Ex1 Step 7 as is then step 13 has you change public IP configurations that simply won't be there as the template is based on VM0 which has no public IP. 

**Lab 08 Exercise 1 [Step 7]**
Step 7

**Lab 08 Exercise 1 [Step 13]**
Step 13

**Comment by awillslo** [comment]
Please leave the lab steps with the first VM as NONE.  Why are we assigning public IP's to vm's going behind a load balancer later on.

**Pull request merged**
