### PR TITLE
Update az104-02a-customRoleDefinition.json

### PR DESCRIPTION
**Pull request by Lvanhanen**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by Lvanhanen** [comment]
jep

**Comment by polichtm** [comment]
Would you mind clarifying why would you want to replace the placeholder with the Id of your own subscription?
rgds
Marcin

**Comment by Lvanhanen** [comment]
accident sorry for that.

-Lauri

**Comment by polichtm** [comment]
appreciate the speedy response
rgds
Marcin

**Pull request closed without merging**
