### PR TITLE
Update LAB_02b-Manage_Governance_via_Azure_Policy.md

### PR DESCRIPTION
**Pull request by cdanvergara**
Modified lines 139 to 143 as the steps described on the instructions to delete the policy assignment are not correct.
Correcting these steps on the instructions.

# Module: 02
## Lab/Demo: 02b

Fixes # .

Changes proposed in this pull request:

- Steps to Delete the Policy Assignment are not right
-This option is available under Overview, not Authoring - Assignments
- Correcting the instructions for these steps

### CODE REVIEW

**Comment by polichtm** [comment]
Hi Cristian,
the original version states:
1. In the **Authoring** section, click **Assignments**. 
Your edit states
1. In the **Overview** section, click over the policy assignment created on the previous task **Require Role tag with Infra value**. 

Can you clarify what's the reason for it?
Here is the corresponding portal interface 

image


rgds
Marcin

**Comment by cdanvergara** [comment]
Hi Marcin, the next step is to Delete the Assignment. 
That option is only available if you navigate to the Assignment from the Overview section.
If you follow the original steps at Authoring - Assignments. You can not delete the assignment from there.

**Comment by polichtm** [comment]
Hi Cristian,
you don't have this option available?

image

rgds
Marcin

**Comment by cdanvergara** [comment]
Hi Marcin
You are 100% right, due to a problem with my resolution I was not seeing that option.
I had to change that and definitely the option is there.
I'll go ahead and delete the PR.

**Comment by polichtm** [comment]
Hi Cristian,
All good – appreciate the follow up…
Rgds
Marcin

**Pull request closed without merging**
