### PR TITLE
Corrected tabbing in code blocks

### PR DESCRIPTION
**Pull request by rlthompson904**
# Module: 09
## Lab/Demo: a, b, and c

Fixes # .

Changes proposed in this pull request:
Corrected syntax used throughout courses of using tabs before code blocks
-
-
-

### CODE REVIEW

**Comment by polichtm** [comment]
Would you mind clarifying what exactly you're trying to accomplish?
rgds
Marcin

**Comment by rlthompson904** [comment]
3 spaces were used in place of tabs on on some code blocks, This could lead to rendering errors depending on the parser used. This pull request would bring the instructions in line with the tabbed standard.

**Comment by polichtm** [comment]
Which parser are you seeing the issues with?
rgds
Marcin

**Comment by rlthompson904** [comment]
And parser following the GitHub markdown spec strictly will fail to render properly https://github.github.com/gfm/#indented-code-blocks.

**Comment by polichtm** [comment]
You mentioned "3 spaces were used in place of tabs on on some code blocks". I don't see any references to using tabs in the documentation you referenced. Would you mind clarifying what specifically you are referring to?
rgds
Marcin

**Comment by rlthompson904** [comment]
I found a more clear example of markdown documentation here. https://www.markdownguide.org/basic-syntax/#code-blocks-1

Within a list, using less that 4 spaces or 1 tab leads to the numbering resetting back to 1.

**Comment by ITBlandMCT** [comment]
Its also specified in the GitHub flavored markdown spec, under 5.2.1 Items 3 & 6 here: https://github.github.com/gfm/#list-items

> 3. “List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab.”

> 6. “To put a code block within a list item, the code block needs to be indented twice — 8 spaces or two tabs.”

**Comment by polichtm** [comment]
Appreciate the clarification. Could you provide the steps to reproduce the problem you are seeing?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response

**Pull request closed without merging**
