### PR TITLE
Update LAB_06-Implement_Network_Traffic_Management.md

### PR DESCRIPTION
**Pull request by jkulbe-msft**
There is only one RG in the lab (RG1). Please also review the architectural image for this lab and change RG4/RG6 to RG1 (../media/lab06.png) - I don't want to mess up the picture by painting around in it.

# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by staleycyn** [comment]
This was just changed by another PR where the requestor pointed out the diagram didn't match the instructions. Does the lab not work, if we match the diagram? - PR #626 - https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/pull/626

**Comment by jkulbe-msft** [comment]
In that case the instructions should mention to create the missing RGs to prevent confusion. This would potentially also mean an update to the Skillable CloudSlice environment is required due to the heavy policies.

**Comment by staleycyn** [comment]
I will let this ride for the teaches next week and see how it plays. Skillable pulls the instructions frequently, but the lab is usually on Wednesdays.

**Comment by staleycyn** [comment]
No further comments on this. If still needed, please open an Issue.

**Comment by staleycyn** [comment]
Write back if you still fee this is needed.

**Pull request closed without merging**
